version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "docker"
      include: "scope"
